# Daftar pemicu awal JUDUL berdasarkan UU 12/2011 dan Tata Naskah Dinas
pemicu_judul:
  - "PRESIDEN"
  - "GUBERNUR"
  - "BUPATI"
  - "WALIKOTA"
  - "MENTERI"
  - "KEPALA"
  - "UNDANG-UNDANG"
  - "PERATURAN"
  - "KEPUTUSAN"
  - "INSTRUKSI"
  - "QANUN"