# Daftar pemicu awal JUDUL
pemicu_judul:
  - "PRESIDEN"
  - "GUBERNUR"
  - "BUPATI"
  - "WALIKOTA"
  - "MENTERI"
  - "KEPALA"
  - "UNDANG-UNDANG"
  - "PERATURAN"
  - "KEPUTUSAN"

# Daftar pemicu Jabatan Pembentuk PPU
pemicu_pembentuk_ppu:
  - "BUPATI"
  - "WALIKOTA"
  - "GUBERNUR"
  - "PRESIDEN"
  - "MENTERI"
  - "KEPALA"